from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import threading
from pathlib import Path
import json

# Import from new modules
from .models import TrainingConfig
from .services.system import get_hardware_info
from .services.validation import validate_dataset_file, clean_dataset_file
from .services.training import start_training_process, stop_training_process

app = FastAPI()

class CleanRequest(BaseModel):
    filename: str

# CORS Configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/system-info")
async def get_system_info():
    return get_hardware_info()

@app.post("/start-training")
async def start_training(config: TrainingConfig):
    # Start training in a separate thread
    thread = threading.Thread(target=start_training_process, args=(config,))
    thread.start()
    
    return {"status": "started", "config": config, "framework": config.framework}

@app.post("/validate-dataset")
async def validate_dataset(file: UploadFile = File(...)):
    return await validate_dataset_file(file)

@app.post("/clean-dataset")
async def clean_dataset(request: CleanRequest):
    return await clean_dataset_file(request.filename)

@app.get("/training-status")
async def get_training_status():
    """Reads the metrics file generated by train_qlora.py"""
    metrics_path = Path(__file__).parent.parent / "LLM_training" / "checkpoints_qlora" / "training_metrics.json"
    if not metrics_path.exists():
        return {"status": "idle", "logs": [], "data": []}
        
    try:
        with open(metrics_path, "r") as f:
            data = json.load(f)
            return data
    except Exception as e:
        return {"status": "error", "error": str(e)}

@app.post("/stop-training")
async def stop_training():
    stop_training_process()
    return {"status": "stopped"}
